@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
REM Generated by Vivado on Wed Jul 09 00:07:25 +0800 2025
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: compile.bat
REM
REM ****************************************************************************

set xv_cxl_lib_path=""
set xv_cpt_lib_path=""
set xv_ext_lib_path=""
set xv_boost_lib_path="D:/vivado/Vivado/2021.2/tps/boost_1_72_0"

REM compile C design sources
echo "xsc -c --gcc_compile_options "-I%xv_boost_lib_path%" -work xil_defaultlib -f pipeline_c.prj"
call xsc  -c --gcc_compile_options "-I%xv_boost_lib_path%" -work xil_defaultlib -f pipeline_c.prj 2> xsc_err.log
call type xsc.log >> compile.log
call type xsc_err.log >> compile.log
call type xsc_err.log
REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -prj pipeline_vlog.prj"
call xvlog  --incr --relax -L uvm -prj pipeline_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
