@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Jul 09 00:07:30 +0800 2025
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************

set xv_cxl_lib_path=""
set xv_cpt_lib_path=""
set xv_ext_lib_path=""
set xv_boost_lib_path="D:/vivado/Vivado/2021.2/tps/boost_1_72_0"

set xv_cxl_win_path=
set PATH=;%PATH%

REM link design libraries
echo "xsc --shared_systemc -lib xil_defaultlib -o libdpi.dll"
call xsc  --shared_systemc -lib xil_defaultlib -o libdpi.dll 2> xsc_err.log
set exit_code=%errorlevel%
call type xsc.log >> elaborate_xsc.log
call type xsc_err.log >> elaborate_xsc.log
call type xsc_err.log
if "%exit_code%"=="1" goto END
REM elaborate design
echo "xelab --incr --debug typical --relax --mt 2 --include "%xv_boost_lib_path%" -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -sv_root "." -sc_lib libdpi.dll --snapshot pipeline_behav xil_defaultlib.pipeline xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 --include "%xv_boost_lib_path%" -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -sv_root "." -sc_lib libdpi.dll --snapshot pipeline_behav xil_defaultlib.pipeline xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
